"""Seed data for the Observatory backend.

The current backend keeps Observatory intentionally thin and additive:
- the registry is a stable seed derived from the current design vocabulary
- topology snapshots are deterministic, with a live timestamp applied at read time
- events are replayed as a short recent log on each SSE subscription
"""

from __future__ import annotations

from copy import deepcopy

REGISTRY: dict[str, object] = {
    "version": 16,
    "updatedAt": "2026-08-09T00:00:00Z",
    "types": [
        {
            "id": "realm",
            "label": "Realm",
            "rune": "ᛞ",
            "icon": "globe",
            "shape": "ring",
            "color": "ice-100",
            "size": 18,
            "border": "solid",
            "canContain": [
                "cluster",
                "host",
                "ravn_long",
                "valkyrie",
                "printer",
                "vaettir",
                "beacon",
            ],
            "parentTypes": [],
            "category": "topology",
            "description": "VLAN-scoped network zone for Niuu runtime entities.",
            "fields": [
                {"key": "vlan", "label": "VLAN", "type": "number", "required": True},
                {"key": "dns", "label": "DNS zone", "type": "string", "required": True},
                {"key": "purpose", "label": "Purpose", "type": "string"},
            ],
        },
        {
            "id": "cluster",
            "label": "Cluster",
            "rune": "ᚲ",
            "icon": "layers",
            "shape": "ring-dashed",
            "color": "ice-200",
            "size": 14,
            "border": "dashed",
            "canContain": [
                "namespace",
                "service",
                "run",
                "ting",
                "bifrost",
                "volundr",
                "valkyrie",
                "warden",
                "mimir",
            ],
            "parentTypes": ["realm"],
            "category": "topology",
            "description": "A runtime cluster nested inside a realm.",
            "fields": [
                {"key": "purpose", "label": "Purpose", "type": "string"},
                {"key": "nodes", "label": "Nodes", "type": "number"},
            ],
        },
        {
            "id": "namespace",
            "label": "Namespace",
            "rune": "ᚾ",
            "icon": "boxes",
            "shape": "ring-dashed",
            "color": "ice-300",
            "size": 12,
            "border": "dashed",
            "canContain": [
                "service",
                "run",
                "ting",
                "bifrost",
                "volundr",
                "ravn_long",
                "valkyrie",
                "warden",
                "mimir",
            ],
            "parentTypes": ["cluster"],
            "category": "topology",
            "description": "Kubernetes namespace grouping runtime workloads.",
            "fields": [
                {"key": "namespace", "label": "Namespace", "type": "string"},
                {"key": "clusterName", "label": "Cluster", "type": "string"},
            ],
        },
        {
            "id": "host",
            "label": "Host",
            "rune": "ᚦ",
            "icon": "server",
            "shape": "rack",
            "color": "slate-400",
            "size": 22,
            "border": "solid",
            "canContain": ["ravn_long", "service"],
            "parentTypes": ["realm"],
            "category": "hardware",
            "description": "Bare-metal or VM host.",
            "fields": [
                {"key": "hw", "label": "Hardware", "type": "string"},
                {"key": "os", "label": "OS", "type": "string"},
                {"key": "cores", "label": "Cores", "type": "number"},
                {"key": "ram", "label": "RAM", "type": "string"},
                {"key": "gpu", "label": "GPU", "type": "string"},
            ],
        },
        {
            "id": "ravn_long",
            "label": "Resident",
            "rune": "ᚱ",
            "icon": "bird",
            "shape": "agent",
            "color": "brand",
            "size": 11,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["host", "cluster", "realm"],
            "category": "agent",
            "description": "Persistent raven agent with a persona and specialty.",
            "fields": [
                {
                    "key": "persona",
                    "label": "Persona",
                    "type": "select",
                    "options": ["thought", "memory", "strength", "battle", "noise", "valkyrie"],
                },
                {"key": "specialty", "label": "Specialty", "type": "string"},
                {"key": "tokens", "label": "Tokens", "type": "number"},
            ],
        },
        {
            "id": "warden",
            "label": "Warden",
            "rune": "ᚱ",
            "icon": "shield",
            "shape": "agent",
            "color": "brand",
            "size": 12,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["namespace", "cluster", "realm"],
            "category": "agent",
            "description": "Autonomous guardian agent bound to a runtime target.",
            "fields": [
                {"key": "persona", "label": "Persona", "type": "string"},
                {"key": "mimirMount", "label": "Mimir mount", "type": "string"},
                {"key": "dreamCycle", "label": "Dream cycle", "type": "string"},
            ],
        },
        {
            "id": "ravn_run",
            "label": "Run agent",
            "rune": "ᚲ",
            "icon": "bird",
            "shape": "triangle",
            "color": "ice-300",
            "size": 8,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["run"],
            "category": "agent",
            "description": "Ephemeral raven conscripted into a run.",
            "fields": [
                {
                    "key": "role",
                    "label": "Role",
                    "type": "select",
                    "options": ["coord", "reviewer", "scholar"],
                },
                {"key": "confidence", "label": "Confidence", "type": "number"},
            ],
        },
        {
            "id": "skuld",
            "label": "Skuld",
            "rune": "ᛜ",
            "icon": "radio",
            "shape": "hex",
            "color": "ice-200",
            "size": 9,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["run", "cluster"],
            "category": "agent",
            "description": "WebSocket broker paired to a run for chat fan-out.",
            "fields": [],
        },
        {
            "id": "valkyrie",
            "label": "Valkyrie",
            "rune": "ᛒ",
            "icon": "shield",
            "shape": "agent",
            "color": "brand-400",
            "size": 13,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["cluster", "realm"],
            "category": "agent",
            "description": "Cluster guardian agent.",
            "fields": [
                {"key": "specialty", "label": "Specialty", "type": "string"},
                {
                    "key": "autonomy",
                    "label": "Autonomy",
                    "type": "select",
                    "options": ["full", "notify", "restricted"],
                },
            ],
        },
        {
            "id": "ting",
            "label": "Ting",
            "rune": "✦",
            "icon": "git-branch",
            "shape": "box",
            "color": "brand",
            "size": 16,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["cluster", "realm"],
            "category": "coordinator",
            "description": "Saga and run orchestrator.",
            "fields": [
                {"key": "activeSagas", "label": "Active sagas", "type": "number"},
                {"key": "pendingRuns", "label": "Pending runs", "type": "number"},
                {
                    "key": "mode",
                    "label": "Mode",
                    "type": "select",
                    "options": ["active", "standby"],
                },
            ],
        },
        {
            "id": "bifrost",
            "label": "Bifröst",
            "rune": "ᚨ",
            "icon": "waves",
            "shape": "pentagon",
            "color": "brand",
            "size": 15,
            "border": "solid",
            "canContain": ["model"],
            "parentTypes": ["cluster", "realm"],
            "category": "coordinator",
            "description": "LLM gateway and routing fabric.",
            "fields": [
                {"key": "reqPerMin", "label": "Req/min", "type": "number"},
                {"key": "cacheHitRate", "label": "Cache hit %", "type": "number"},
                {"key": "providers", "label": "Providers", "type": "tags"},
            ],
        },
        {
            "id": "volundr",
            "label": "Völundr",
            "rune": "ᚲ",
            "icon": "hammer",
            "shape": "box",
            "color": "brand",
            "size": 16,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["cluster", "realm"],
            "category": "coordinator",
            "description": "Session forge for development pods and workspaces.",
            "fields": [
                {"key": "activeSessions", "label": "Active", "type": "number"},
                {"key": "maxSessions", "label": "Max", "type": "number"},
            ],
        },
        {
            "id": "mimir",
            "label": "Mímir",
            "rune": "ᛗ",
            # A store, drawn as one. There is no longer a single Mímir to make
            # the centrepiece of the canvas: every cluster has one, and a
            # workflow session draws one for each store it provisions or
            # mounts. At that count the old well — a lit, breathing disc the
            # size of a cluster, drawn above everything — stopped reading as
            # emphasis and started reading as noise.
            "icon": "database",
            "shape": "cylinder",
            "color": "ice-100",
            "size": 11,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["cluster", "realm"],
            "category": "knowledge",
            "description": "Primary knowledge and memory index.",
            "fields": [
                {"key": "pages", "label": "Pages", "type": "number"},
                {"key": "writes", "label": "Writes", "type": "number"},
                {"key": "mountCount", "label": "Mounts", "type": "number"},
            ],
        },
        {
            "id": "service",
            "label": "Service",
            "rune": "ᛦ",
            "icon": "box",
            "shape": "box",
            "color": "ice-300",
            "size": 8,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["cluster", "host"],
            "category": "infrastructure",
            "description": "Runtime service or workload.",
            "fields": [
                {
                    "key": "svcType",
                    "label": "Type",
                    "type": "select",
                    "options": [
                        "rabbitmq",
                        "auth",
                        "secrets",
                        "authz",
                        "database",
                        "inference",
                        "registry",
                        "gitops",
                        "dashboard",
                        "logs",
                        "traces",
                        "media",
                        "manufacturing",
                        "orchestrator",
                    ],
                }
            ],
        },
        {
            "id": "flock",
            "label": "Flock",
            "rune": "ᚹ",
            "icon": "share-2",
            # A mesh, not a place: it has no cluster and holds nothing. It is
            # drawn so the agents on it have something to connect to.
            "shape": "halo",
            "color": "amber-300",
            "size": 11,
            "border": "dashed",
            "canContain": [],
            "parentTypes": [],
            "category": "topology",
            "description": "Agent mesh that Valkyries and residents belong to.",
            "fields": [{"key": "flockId", "label": "Flock ID", "type": "string"}],
        },
        {
            "id": "cloud",
            "label": "Vendor cloud",
            "rune": "ᚱ",
            "icon": "cloud",
            # A region, not an object: it holds the models a vendor serves and
            # sits outside every cluster, because that is where they run.
            "shape": "cloud",
            "color": "violet-300",
            "size": 18,
            "border": "dashed",
            "canContain": ["model"],
            "parentTypes": [],
            "category": "topology",
            "description": "Models served from outside the estate, grouped by vendor.",
            "fields": [{"key": "vendor", "label": "Vendor", "type": "string"}],
        },
        {
            "id": "model",
            "label": "LLM Model",
            "rune": "ᛖ",
            "icon": "cpu",
            # A model is not a plain workload: it is the thing that costs money
            # per token, so it carries its own mark and a utilisation ring.
            "shape": "hex-flat",
            "color": "slate-300",
            "size": 13,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["bifrost", "realm", "cloud"],
            "category": "knowledge",
            "description": "Inference model endpoint behind Bifröst.",
            "fields": [
                {"key": "provider", "label": "Provider", "type": "string"},
                {
                    "key": "location",
                    "label": "Location",
                    "type": "select",
                    "options": ["internal", "external"],
                },
            ],
        },
        {
            "id": "printer",
            "label": "Resin Printer",
            "rune": "ᛈ",
            "icon": "printer",
            # `shape` is seed-owned (see `_SEED_OWNED_KEYS`), so setting this
            # through the registry API alone would silently revert on the next
            # version bump. A print farm drawn as the same plain box any
            # unrecognised workload gets is the one thing an operator scanning
            # for their machines cannot afford.
            "shape": "printer",
            "color": "slate-400",
            "size": 10,
            "border": "solid",
            "canContain": [],
            # A printer reached through a gateway running in a cluster sits in
            # that cluster's namespace; one on a bench sits in the realm.
            "parentTypes": ["realm", "namespace", "cluster"],
            "category": "device",
            "description": "Manufacturing printer node.",
            "fields": [{"key": "model", "label": "Model", "type": "string"}],
        },
        {
            "id": "vaettir",
            "label": "Vættir Room Node",
            "rune": "ᚹ",
            "icon": "mic",
            "shape": "square-sm",
            "color": "slate-400",
            "size": 9,
            "border": "solid",
            "canContain": [],
            "parentTypes": ["realm"],
            "category": "device",
            "description": "Room presence node.",
            "fields": [{"key": "sensors", "label": "Sensors", "type": "tags"}],
        },
        {
            "id": "beacon",
            "label": "Presence Beacon",
            "rune": "ᚠ",
            "icon": "wifi",
            # A beacon emits; it pings rather than sitting there.
            "shape": "beacon",
            "color": "slate-400",
            "size": 9,
            "border": "dashed",
            "canContain": [],
            "parentTypes": ["realm"],
            "category": "device",
            "description": "BLE presence beacon.",
            "fields": [],
        },
        {
            "id": "run",
            "label": "Run",
            "rune": "ᚷ",
            "icon": "users",
            "shape": "halo",
            "color": "brand",
            "size": 50,
            "border": "dashed",
            "canContain": ["ravn_run", "skuld"],
            "parentTypes": ["cluster"],
            "category": "composite",
            "description": "Ephemeral flock executing a saga.",
            "fields": [
                {"key": "purpose", "label": "Purpose", "type": "string"},
                {
                    "key": "state",
                    "label": "State",
                    "type": "select",
                    "options": ["forming", "working", "dissolving"],
                },
                {"key": "composition", "label": "Composition", "type": "tags"},
            ],
        },
    ],
}


def get_registry() -> dict[str, object]:
    """Return a copy of the current registry payload."""
    return deepcopy(REGISTRY)
